---
title: "Descriptives"
author: "KW"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)

pacman::p_load(
	dplyr, 
	here,
	ggplot2
	)

```

```{r}
# --------------------------------
# 1. Dataset
# --------------------------------
fyc <- readRDS(here::here("data_processed/fyc.RDS")) |> 
	mutate(ind_gt0 = ifelse(TOTEXPYY > 0, 1, 0)) |> 
	mutate(log_totexpy = log(TOTEXPYY), na.rm=TRUE) |> 
	# don't need weights, not going to do weighted sampling
	select(
		, year:DUPERSID
		, TOTEXPYY
		, z_TOTEXPYY
		, ind_gt0
		, log_totexpy
		, PANEL
		, INSCOVYY
		, UNINSYY
		, INSCOPE   # it has the same values as INSCOPYY
		, MARRYYYX
		, fct_MARRYYYX
		, FAMSZEYR
		, PCS42:MCS42
		, SEX
		, HISPANX
		, EDUCYR, HIDEG, EDUYRDG, EDRECODE
		, POVCATYY
		, fct_POVCATYY
		, ARTHDX:HIBPDX
		, RAREDX
		, starts_with("RACE")
	)

fyc_post <- fyc |> 
	filter(pre_post=="post")
# 11302 
```  

How many do I have > $20k? 

```{r}
n_gt50k <- fyc |> filter(TOTEXPYY>50000) |> nrow()

n_gt20k <- fyc |> filter(TOTEXPYY>20000) |> nrow()

fyc_le50k <- fyc |> 
	filter(TOTEXPYY<=50000)

fyc_le20k <- fyc |> 
	filter(TOTEXPYY<=20000)
```  

In my dataset, there are `r n_gt20k` values greater than \$20,000 and `r n_gt50k` values greater than \$50,000. 

In Deb's paper, they had n=317 values gt 20k and n=35 values greater than 50k. 

### Histograms  

In Deb's paper, they did histograms with truncation at 50k and 20k. Mimic that so it shows something. 

Without truncating, shows nothing really: 

```{r hist_asis}
ggplot(
	fyc, aes(x=TOTEXPYY))+
	geom_histogram(bins=100)
```

```{r hist_le50k}
(hist_le50k <- ggplot(
	fyc_le50k, aes(x=TOTEXPYY))+
	geom_histogram(
		aes(y = after_stat(count)/sum(after_stat(count))), 
		fill="steelblue", bins=40)+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black")
	)+
	scale_x_continuous(expand=c(0.02,0))+
	scale_y_continuous(expand=c(0,0)) +
	ylab("Fraction")+
	xlab("Total health care expenditures (dollars)"))
```  


```{r hist_le20k}
fyc_le20k_gt0 <- fyc_le20k |> 
	filter(TOTEXPYY > 0)

hist_le20k <- ggplot(fyc_le20k_gt0, aes(x=TOTEXPYY))+
	geom_histogram(
		aes(y = after_stat(count)/sum(after_stat(count))), 
		fill="steelblue", bins=40)+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black")
	)+
	scale_x_continuous(expand=c(0.02,0))+
	scale_y_continuous(expand=c(0,0), limits=c(0, 0.3)) +
	ylab("Fraction")+
	xlab("Total health care expenditures (dollars)")+
	annotate(
		"text",
		x=17500, y=0.05,
		label = glue::glue(n_gt20k, " have\nexpenditures >$20k"))

```  

```{r bar_gt0}

avg_1s_gt0 <- round(mean(fyc$ind_gt0), digits=3)
avg_0s_gt0 <- 1-avg_1s_gt0

bar_gt0_prep <- data.frame(
	Expenditure = factor(c(0, 1), levels = c(0, 1)),
	Fraction = c(avg_0s_gt0, avg_1s_gt0),
	Label = c(
		paste0(avg_0s_gt0*100,"% have\nexpenditures = $0"), 
		paste0(avg_1s_gt0*100,"% have\nexpenditures >$0"))
)

(bar_gt0 <- ggplot(
	bar_gt0_prep, aes(x=Expenditure, y=Fraction))+
	geom_bar(stat="identity", fill="steelblue", width = 0.6)+
	geom_text(aes(label = Label), vjust = -0.5)+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black"),
	)+
	scale_y_continuous(
		expand=c(0,0), 
		limits = c(0, 0.9))+
	labs(
		x = "Are health care expenditures positive (or 0)?",
		y = "Fraction"
	)+
	# theme_minimal(base_size = 12)+
	theme(
		axis.title.x = element_text(),
		axis.title.y = element_text())
	)

```


```{r hist_log}
fyc_log <- fyc |> 
	filter(TOTEXPYY > 0)

(hist_log <- ggplot(
	fyc_log, aes(x=log_totexpy))+
		geom_histogram(
		aes(y = after_stat(count)/sum(after_stat(count))), 
		fill="steelblue", bins=40)+
	# geom_histogram(
	# 	aes(y = ..density..), bins=30, fill="steelblue", alpha = 0.6)+
	# geom_density(color = "darkgreen")+
	# stat_function(
	# 	fun = dnorm,
	# 	args = list(mean = mean(fyc_log$log_totexpy), sd=sd(fyc_log$log_totexpy)),
	# 	color = "darkgreen"
	# )+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black")
	)+
	scale_x_continuous(expand=c(0.02,0))+
	scale_y_continuous(expand=c(0,0), limits = c(0, 0.09)) +
	ylab("Fraction")+
	xlab("ln(Total health care expenditures), if>0"))

```    

Combine plots  

```{r combo_plots}
library(cowplot)

all_plots <- plot_grid(
	plot_grid(hist_le50k, bar_gt0, ncol = 2, labels = c("a", "b")), 
	NULL,
	plot_grid(hist_le20k, hist_log, ncol = 2, labels = c("c", "d")), 
	ncol = 1,
	# labels = c("a", "b", "c", "d"),
	rel_heights = c(1, 0.15, 1)
	)


# final_plot <- plot_grid(
# 	ggdraw() + 
# 		draw_label(
# 			"Overall Title: Health Care Expenditure Analysis", 
# 			fontface = 'bold', 
# 			size = 12, 
# 			hjust=2.10),
# 	all_plots,
# 	ncol = 1,
# 	rel_heights = c(0.1, 1)
# 	# Adjust title height vs. plot height
# )

```  

## X  

```{r select_x_1}
# Get descriptives from entire dataset (if can't do DiD, do post-only later): 
fyc_cor <- fyc |> 
	# don't need logged var, ID vars etc. INSCOPE was a subsetting var so don't need that either
	select(-c(DUID, PID, DUPERSID, z_TOTEXPYY, log_totexpy, PANEL, INSCOPE, EDUCYR, HIDEG, EDUYRDG, EDRECODE, RACEX, RACETHNX, RACEVER, RACEV1X, RACETHX, RACEV2X)) |> 
	select(where(is.numeric))

# Descriptives 
pacman::p_load(gtsummary)
tbl_summary(
	data = fyc_cor,
	by=ind_tx
)
# Add p-value to see which to include (?)

correlation_matrix <- cor(fyc_cor |> select(-c(year, ind_gt0)))
# Select Variables 
correlation_matrix

pacman::p_load(corrplot)
corrplot(cor(fyc_cor))
```




