---
title: "Descriptives"
author: "KW"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)

pacman::p_load(
	dplyr, 
	here,
	ggplot2
	)

set.seed(123)

```

```{r}
# --------------------------------
# 1. Dataset
# --------------------------------
fyc <- readRDS(here::here("data_processed/fyc.RDS")) |> 
	mutate(ind_gt0 = ifelse(TOTEXPYY > 0, 1, 0))

```  

How many do I have > $20k? 

```{r}
n_gt50k <- fyc |> filter(TOTEXPYY>50000) |> nrow()

n_gt20k <- fyc |> filter(TOTEXPYY>20000) |> nrow()

fyc_le50k <- fyc |> 
	filter(TOTEXPYY<=50000)

fyc_le20k <- fyc |> 
	filter(TOTEXPYY<=20000)
```  

In my dataset, there are `r n_gt20k` values greater than \$20,000 and `r n_gt50k` values greater than \$50,000. 

In Deb's paper, they had n=317 values gt 20k and n=35 values greater than 50k. 


### Histograms  

In Deb's paper, they did histograms with truncation at 50k and 20k. Mimic that so it shows something. 

Without truncating, shows nothing really: 

```{r hist_asis}
ggplot(
	fyc, aes(x=TOTEXPYY))+
	geom_histogram(bins=100)
```

```{r hist_le50k}
(hist_le50k <- ggplot(
	fyc_le50k, aes(x=TOTEXPYY))+
	geom_histogram(
		aes(y = after_stat(count)/sum(after_stat(count))), 
		fill="steelblue", bins=40)+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black")
	)+
	scale_x_continuous(expand=c(0.02,0))+
	scale_y_continuous(expand=c(0,0)) +
	ylab("Fraction")+
	xlab("Total health care expenditures (dollars)"))
```  


```{r hist_le20k}
(hist_le20k <- ggplot(
	fyc_le20k, aes(x=TOTEXPYY))+
	geom_histogram(
		aes(y = after_stat(count)/sum(after_stat(count))), 
		fill="steelblue", bins=40)+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black")
	)+
	scale_x_continuous(expand=c(0.02,0))+
	scale_y_continuous(expand=c(0,0)) +
	ylab("Fraction")+
	xlab("Total health care expenditures (dollars)"))+
	annotate(
		"text",
		x=17500, y=0.05,
		label = glue::glue(n_gt20k, " have\nexpenditures >$20k"))

```  

```{r bar_gt0}

avg_1s_gt0 <- round(mean(fyc$ind_gt0), digits=3)
avg_0s_gt0 <- 1-avg_1s_gt0

bar_gt0_prep <- data.frame(
	Expenditure = factor(c(0, 1), levels = c(0, 1)),
	Fraction = c(avg_0s_gt0, avg_1s_gt0),
	Label = c(
		paste0(avg_0s_gt0*100,"% have\nexpenditures = $0"), 
		paste0(avg_1s_gt0*100,"% have\nexpenditures >$0"))
)

(bar_gt0 <- ggplot(
	bar_gt0_prep, aes(x=Expenditure, y=Fraction))+
	geom_bar(stat="identity", fill="steelblue", width = 0.6))+
	geom_text(aes(label = Label), vjust = -0.5)+
	theme(
		panel.background = element_blank(), 
		panel.border = element_rect(color="black", fill=NA),
		axis.ticks=element_line(color="black")
	)+
	scale_y_continuous(
		expand=c(0,0), 
		limits = c(0, 0.8))+
	labs(
		x = "Are health care expenditures positive (or 0)?",
		y = "Fraction of individuals"
	)+
	theme_minimal(base_size = 12)+
	theme(
		axis.title.x = element_text(margin = margin(t=10)),
		axis.title.y = element_text(margin = margin(r=10))
	)

```

