---
title: "Untitled"
author: "Trial"
date: "8/8/2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lme4)
library(MASS)  # for mvrnorm

simulate_panel_data <- function(n, magnitude, p_treated, sigma_u = 0.5, sigma_e = 0.3, rho = 0.8) {
  T <- 2  # Pre and Post
  
  # Individual-level IDs
  ids <- rep(1:n, each = T)
  time <- rep(0:1, times = n)  # 0 = pre, 1 = post
  ind_post <- time
  
  # Treatment (constant per person)
  ind_tx_i <- rbinom(n, 1, p_treated)
  ind_tx <- rep(ind_tx_i, each = T)
  
  # Demographics (fixed per ID)
  ind_female_i <- rbinom(n, 1, 0.5)
  HISPANX_i <- rbinom(n, 1, 0.2)
  INSCOV_i <- sample(1:3, n, replace = TRUE)
  
  ind_female <- rep(ind_female_i, each = T)
  HISPANX <- rep(HISPANX_i, each = T)
  INSCOV <- factor(rep(INSCOV_i, each = T))
  
  # Time-varying covariate: PCS42 with pre-post correlation
  PCS_corr <- matrix(c(1, rho, rho, 1), 2, 2)
  PCS_raw <- MASS::mvrnorm(n, mu = c(50, 50), Sigma = PCS_corr)
  PCS42 <- as.vector(t(PCS_raw))  # interleave PCS42_pre, PCS42_post
  
  # Random intercepts (same across time)
  u_i <- rnorm(n, 0, sigma_u)
  u <- u_i[ids]
  
  ### Part 1: Binary outcome
  lp_bin <- -1 + 0.5 * ind_post + 0.7 * ind_tx + magnitude * ind_post * ind_tx +
    0.3 * ind_female - 0.2 * HISPANX + 0.1 * PCS42 + u
  prob_gt0 <- plogis(lp_bin)
  ind_gt0 <- rbinom(n * T, 1, prob_gt0)
  
  ### Part 2: Continuous outcome (TOTEXPYY) if ind_gt0 == 1
  lp_cont <- 7 + 0.4 * ind_post + 0.6 * ind_tx + magnitude * ind_post * ind_tx +
    0.2 * ind_female - 0.1 * HISPANX + 0.15 * PCS42 + u
  eps <- rnorm(n * T, 0, sigma_e)
  log_TOTEXPYY <- lp_cont + eps
  TOTEXPYY <- ifelse(ind_gt0 == 1, exp(log_TOTEXPYY), NA)
  
  # Assemble the final data
  data.frame(
    DUPERSID = factor(ids),
    ind_post = ind_post,
    ind_tx = ind_tx,
    ind_female = ind_female,
    HISPANX = HISPANX,
    PCS42 = PCS42,
    INSCOV = INSCOV,
    ind_gt0 = ind_gt0,
    TOTEXPYY = TOTEXPYY
  )
}

```


```{r}
# Simulate with 1000 people, magnitude = 2, and 50% treated
df <- simulate_panel_data(n = 1000, magnitude = 2, p_treated = 0.5)

View(df)

# Check: should see each ID with same ind_tx, ind_female, etc.
table(df$ind_tx, df$ind_post)

```


